gem 'rack'
gem 'feedtools', :require => 'feed_tools'
gem 'haml'
gem 'sass'
gem 'sequel'
gem 'sqlite3-ruby'
gem 'sinatra', '~> 1.4'
gem 'uuidtools'
gem 'rake'
gem 'bacon'
gem 'rubypants'

gem 'addressable'
gem 'nokogiri'

gem 'ruby-openid', :require => 'openid'
